
sudo: required
os: osx
language: node_js

notifications:
  email: true

node_js: "8.5.0"

addons:
  firefox: latest

before_install:
- export DISPLAY=:99.0

before_script:
- npm install

script: ./node_modules/karma/bin/karma start test/karma.conf.js --single-run